sudo: required
services:
  - docker

before_install:
  - docker build -t jxrdy/fibo-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true jxrdy/fibo-test npm test

after_succes:
  - docker build -t jxrdy/multi-client ./client
  - docker build -t jxrdy/multi-nginx ./nginx
  - docker build -t jxrdy/multi-server ./server
  - docker build -t jxrdy/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jxrdy/multi-client
  - docker push jxrdy/multi-nginx
  - docker push jxrdy/multi-server
  - docker push jxrdy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket_name: 'elasticbeanstalk-eu-west-1-637174301702'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
